import { TitleDefinition, TitleId } from "@/features/title/types";

export const TITLES: Record<TitleId, TitleDefinition> = {
  apex_predator: {
    id: "apex_predator",
    name: "Apex Predator",
    category: "ranking",
    condition: "ランキング1位達成（PCまたはMOBILE）",
    description: "頂点捕食者。ランキングの頂点に君臨する者。",
    badgeColor: {
      bg: "bg-red-950/40",
      border: "border-red-500",
      text: "text-red-400",
      glow: "shadow-[0_0_15px_rgba(239,68,68,0.5)]",
    },
  },
  synapse_overload: {
    id: "synapse_overload",
    name: "Synapse Overload",
    category: "game_mode",
    condition: "ゲームモード 全ラウンド Godlike クリア",
    description: "神経過負荷。極限の反射神経で全ラウンドを制覇。",
    badgeColor: {
      bg: "bg-amber-950/40",
      border: "border-yellow-400",
      text: "text-yellow-300",
      glow: "shadow-[0_0_15px_rgba(250,204,21,0.5)]",
    },
  },
  high_frequency: {
    id: "high_frequency",
    name: "High-Frequency",
    category: "game_mode",
    condition: "ゲームモード 全ラウンド Excellent 以上クリア",
    description: "高周波反応。安定して超高速を維持した証。",
    badgeColor: {
      bg: "bg-cyan-950/40",
      border: "border-cyan-400",
      text: "text-cyan-300",
      glow: "shadow-[0_0_15px_rgba(34,211,238,0.5)]",
    },
  },
  untouchable: {
    id: "untouchable",
    name: "Untouchable",
    category: "battle_mode",
    condition: "バトルモード ノーダメージ完封勝利",
    description: "触れさせない完全勝利。相手の攻撃を一切許さず制圧。",
    badgeColor: {
      bg: "bg-purple-950/40",
      border: "border-[#bc13fe]",
      text: "text-[#d866ff]",
      glow: "shadow-[0_0_15px_rgba(188,19,254,0.5)]",
    },
  },
  gods_reflex: {
    id: "gods_reflex",
    name: "God’s Reflex",
    category: "battle_mode",
    condition: "バトルモード Godlike 5連コンボ（最大倍率）達成",
    description: "神の領域の反射神経。極限のストリークを叩き出した証。",
    badgeColor: {
      bg: "bg-yellow-950/40",
      border: "border-yellow-500",
      text: "text-yellow-400",
      glow: "shadow-[0_0_15px_rgba(234,179,8,0.5)]",
    },
  },
  flow_state: {
    id: "flow_state",
    name: "Flow State",
    category: "battle_mode",
    condition: "バトルモード Excellent 5連コンボ（最大倍率）達成",
    description: "研ぎ澄まされた極限集中。ゾーンに入った境地。",
    badgeColor: {
      bg: "bg-blue-950/40",
      border: "border-blue-400",
      text: "text-blue-300",
      glow: "shadow-[0_0_15px_rgba(96,165,250,0.5)]",
    },
  },
  awakened: {
    id: "awakened",
    name: "Awakened",
    category: "play_count",
    condition: "ゲームモード 通算10回プレイ",
    description: "覚醒の兆し。己の反応速度の可能性に目覚めた者。",
    badgeColor: {
      bg: "bg-emerald-950/40",
      border: "border-emerald-500",
      text: "text-emerald-400",
      glow: "shadow-[0_0_15px_rgba(16,185,129,0.4)]",
    },
  },
  overclocked: {
    id: "overclocked",
    name: "Overclocked",
    category: "play_count",
    condition: "ゲームモード 通算50回プレイ",
    description: "リミッター解除・限界突破。神経回路が加速する。",
    badgeColor: {
      bg: "bg-teal-950/40",
      border: "border-teal-400",
      text: "text-teal-300",
      glow: "shadow-[0_0_15px_rgba(45,212,191,0.4)]",
    },
  },
  neural_master: {
    id: "neural_master",
    name: "Neural Master",
    category: "play_count",
    condition: "ゲームモード 通算100回プレイ",
    description: "神経を統べる歴戦の達人。数多の試練を潜り抜けた証。",
    badgeColor: {
      bg: "bg-violet-950/40",
      border: "border-violet-500",
      text: "text-violet-300",
      glow: "shadow-[0_0_15px_rgba(139,92,246,0.5)]",
    },
  },
  contender: {
    id: "contender",
    name: "Contender",
    category: "battle_wins",
    condition: "バトルモード 通算10勝達成",
    description: "闘技場の有望株。対戦の厳しさを知り頭角を現した者。",
    badgeColor: {
      bg: "bg-sky-950/40",
      border: "border-sky-400",
      text: "text-sky-300",
      glow: "shadow-[0_0_15px_rgba(56,189,248,0.4)]",
    },
  },
  veteran: {
    id: "veteran",
    name: "Veteran",
    category: "battle_wins",
    condition: "バトルモード 通算50勝達成",
    description: "歴戦の猛者。数々の死闘を制してきた勝負師。",
    badgeColor: {
      bg: "bg-indigo-950/40",
      border: "border-indigo-400",
      text: "text-indigo-300",
      glow: "shadow-[0_0_15px_rgba(129,140,248,0.5)]",
    },
  },
  speed_gladiator: {
    id: "speed_gladiator",
    name: "Speed Gladiator",
    category: "battle_wins",
    condition: "バトルモード 通算100勝達成",
    description: "光速の剣闘士。アリーナにその名を轟かせる百戦錬磨の覇者。",
    badgeColor: {
      bg: "bg-orange-950/40",
      border: "border-orange-500",
      text: "text-orange-400",
      glow: "shadow-[0_0_15px_rgba(249,115,22,0.5)]",
    },
  },
  clutch_god: {
    id: "clutch_god",
    name: "Clutch God",
    category: "special",
    condition: "残HP 100ms 未満からの逆転勝利",
    description:
      "クラッチ：土壇場を制する者。ミリ秒の瀕死から勝利を手繰り寄せた奇跡。",
    badgeColor: {
      bg: "bg-rose-950/40",
      border: "border-rose-500",
      text: "text-rose-400",
      glow: "shadow-[0_0_15px_rgba(244,63,94,0.5)]",
    },
  },
  quantum_mirror: {
    id: "quantum_mirror",
    name: "Quantum Mirror",
    category: "special",
    condition: "同じ試合で引き分け（DRAW）を2回以上発生させる",
    description: "ミリ秒単位で完全に同期した奇跡。時空の狭間で出会った双子星。",
    badgeColor: {
      bg: "bg-fuchsia-950/40",
      border: "border-fuchsia-400",
      text: "text-fuchsia-300",
      glow: "shadow-[0_0_15px_rgba(232,121,249,0.5)]",
    },
  },
  light_speed: {
    id: "light_speed",
    name: "Light-Speed",
    category: "special",
    condition: "単発で 150ms 未満（超神速）を叩き出す",
    description: "人類を超越した速度域。光の速さに肉薄した奇跡の一撃。",
    badgeColor: {
      bg: "bg-amber-950/40",
      border: "border-amber-400",
      text: "text-amber-300",
      glow: "shadow-[0_0_15px_rgba(251,191,36,0.6)]",
    },
  },
  trigger_happy: {
    id: "trigger_happy",
    name: "Trigger Happy",
    category: "special",
    condition: "通算フライング回数が 50回に到達",
    description:
      "指が勝手に動いてしまう人。速さを求めるあまり魂が先走る衝動の塊。",
    badgeColor: {
      bg: "bg-zinc-900/60",
      border: "border-zinc-400",
      text: "text-zinc-300",
      glow: "shadow-[0_0_10px_rgba(161,161,170,0.4)]",
    },
  },
};

export const TITLE_LIST = Object.values(TITLES);
